# Generated by Django 4.2 on 2023-05-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_rename_master_id_booking_master_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='status',
            field=models.BooleanField(choices=[(1, 'Active'), (2, 'Day off'), (3, 'Sick leave'), (9, 'Fired')], default=True),
        ),
    ]
