# Generated by Django 4.2 on 2023-05-14 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0004_alter_master_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='client',
            field=models.IntegerField(default=1),
        ),
    ]
