# Generated by Django 4.2 on 2023-05-15 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0005_booking_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='time_required',
            new_name='required_time',
        ),
    ]
