# Generated by Django 4.2 on 2023-05-15 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0007_rename_name_service_service_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='rank',
            field=models.IntegerField(choices=[(1, 'Junior'), (2, 'Senior')]),
        ),
        migrations.AlterField(
            model_name='master',
            name='status',
            field=models.BooleanField(choices=[(1, 'Active'), (2, 'Day off'), (3, 'Sick leave'), (9, 'Fired')], default=2),
        ),
    ]
