# Generated by Django 4.2 on 2023-05-15 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0008_alter_master_rank_alter_master_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Day off'), (3, 'Sick leave'), (9, 'Fired')], default=2),
        ),
    ]
