# Generated by Django 4.2 on 2023-05-15 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0009_alter_master_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='date',
        ),
    ]
